[theme]
primaryColor = "#00E5FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#151A22"
textColor = "#E6F1FF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
